#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

EXPECTED_SUBSCRIPTION_ID="1e0a3a33-8911-465b-8923-82807107dfe1"
EXPECTED_TENANT_ID="5b973f99-77df-4beb-b27d-aa0c70b8482c"
AZURE_LOCATION="westeurope"
RESOURCE_GROUP="flash-trips-prod-rg"
GITHUB_ENVIRONMENT="production"
DEPLOYMENT_NAME="flash-trips-production"
TEMPLATE_FILE="infra/azure/production.bicep"

fail() {
  printf '  %s✗ %s%s\n' "$RED" "$*" "$RESET" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "Required command not found: $1"
}

banner "Flash Trips Azure production setup"

stage "Validate accounts"
say "This setup uses the authorized Visual Studio Enterprise Subscription."
for command in az gh jq git curl; do
  require_command "$command"
done
az account show >/dev/null || fail "Azure CLI is not authenticated. Run: az login"
gh auth status >/dev/null || fail "GitHub CLI is not authenticated. Run: gh auth login"

SUBSCRIPTION_ID="$(az account show --query id --output tsv)"
TENANT_ID="$(az account show --query tenantId --output tsv)"
SUBSCRIPTION_NAME="$(az account show --query name --output tsv)"
REPOSITORY="$(gh repo view --json nameWithOwner --jq .nameWithOwner)"
GITHUB_SUBJECT_PREFIX="$(gh api \
  "repos/$REPOSITORY/actions/oidc/customization/sub" \
  --jq .sub_claim_prefix)"
[[ "$SUBSCRIPTION_ID" == "$EXPECTED_SUBSCRIPTION_ID" ]] ||
  fail "Active subscription is $SUBSCRIPTION_ID, expected $EXPECTED_SUBSCRIPTION_ID"
[[ "$TENANT_ID" == "$EXPECTED_TENANT_ID" ]] ||
  fail "Active tenant is $TENANT_ID, expected $EXPECTED_TENANT_ID"
[[ "$REPOSITORY" == "Tirso0882/flash-trips" ]] ||
  fail "Current repository is $REPOSITORY, expected Tirso0882/flash-trips"
[[ "$GITHUB_SUBJECT_PREFIX" == repo:* ]] ||
  fail "GitHub returned an invalid OIDC subject prefix"
say "Azure subscription: $SUBSCRIPTION_NAME ($SUBSCRIPTION_ID)"
say "Azure tenant: $TENANT_ID"
say "GitHub repository: $REPOSITORY"
confirm "Are you still authorized to create Flash Trips resources here?" ||
  fail "Authorization was not confirmed"

stage "Confirm production boundary"
say "The production group will be $RESOURCE_GROUP in $AZURE_LOCATION."
say "It includes ACR Basic, Container Apps consumption, Key Vault, and monitoring."
warn "These resources can incur Azure charges. PostgreSQL is not included."
open_url "https://portal.azure.com/#view/Microsoft_Azure_CostManagement/Menu/~/costanalysis"
step "Review the selected subscription and its current cost controls."
confirm "Continue to provider registration and a read-only deployment preview?" ||
  fail "Production setup cancelled"

stage "Preview infrastructure"
say "Registering Azure resource providers. Registration is subscription metadata."
for provider in \
  Microsoft.App \
  Microsoft.ContainerRegistry \
  Microsoft.Insights \
  Microsoft.KeyVault \
  Microsoft.ManagedIdentity \
  Microsoft.OperationalInsights; do
  az provider register --namespace "$provider" --wait
done
az bicep version >/dev/null 2>&1 || az bicep install
az bicep build --file "$TEMPLATE_FILE" --stdout >/dev/null
say "Azure will now calculate the exact changes without creating resources."
az deployment sub what-if \
  --name "$DEPLOYMENT_NAME" \
  --location "$AZURE_LOCATION" \
  --template-file "$TEMPLATE_FILE" \
  --parameters \
    githubEnvironment="$GITHUB_ENVIRONMENT" \
    githubSubjectPrefix="$GITHUB_SUBJECT_PREFIX" \
    location="$AZURE_LOCATION" \
    resourceGroupName="$RESOURCE_GROUP"
confirm "Does the preview match the approved app baseline?" ||
  fail "Infrastructure preview was not approved"

stage "Provision app baseline"
warn "This creates billable Azure resources and purge-protected Key Vault metadata."
confirm "Create the production resources now?" ||
  fail "Infrastructure creation was not approved"
DEPLOYMENT_JSON="$(az deployment sub create \
  --name "$DEPLOYMENT_NAME" \
  --location "$AZURE_LOCATION" \
  --template-file "$TEMPLATE_FILE" \
  --parameters \
    githubEnvironment="$GITHUB_ENVIRONMENT" \
    githubSubjectPrefix="$GITHUB_SUBJECT_PREFIX" \
    location="$AZURE_LOCATION" \
    resourceGroupName="$RESOURCE_GROUP" \
  --output json)"

ACR_NAME="$(jq -r '.properties.outputs.acrName.value' <<<"$DEPLOYMENT_JSON")"
API_APP_NAME="$(jq -r '.properties.outputs.apiAppName.value' <<<"$DEPLOYMENT_JSON")"
API_FQDN="$(jq -r '.properties.outputs.apiFqdn.value' <<<"$DEPLOYMENT_JSON")"
DEPLOY_CLIENT_ID="$(jq -r '.properties.outputs.deployClientId.value' <<<"$DEPLOYMENT_JSON")"
KEY_VAULT_NAME="$(jq -r '.properties.outputs.keyVaultName.value' <<<"$DEPLOYMENT_JSON")"
RELEASE_CLIENT_ID="$(jq -r '.properties.outputs.releaseClientId.value' <<<"$DEPLOYMENT_JSON")"
WEB_APP_NAME="$(jq -r '.properties.outputs.webAppName.value' <<<"$DEPLOYMENT_JSON")"
WEB_FQDN="$(jq -r '.properties.outputs.webFqdn.value' <<<"$DEPLOYMENT_JSON")"
for value in \
  "$ACR_NAME" \
  "$API_APP_NAME" \
  "$API_FQDN" \
  "$DEPLOY_CLIENT_ID" \
  "$KEY_VAULT_NAME" \
  "$RELEASE_CLIENT_ID" \
  "$WEB_APP_NAME" \
  "$WEB_FQDN"; do
  [[ -n "$value" && "$value" != "null" ]] || fail "Azure deployment returned an empty output"
done
say "Created resource group: $RESOURCE_GROUP"
say "Created registry: $ACR_NAME"
say "Created Key Vault: $KEY_VAULT_NAME"

stage "Configure GitHub"
say "Creating a production approval gate and writing public OIDC identifiers."
GITHUB_USER_ID="$(gh api user --jq .id)"
ENVIRONMENT_PAYLOAD="$(jq -n \
  --argjson reviewerId "$GITHUB_USER_ID" \
  '{
    wait_timer: 0,
    prevent_self_review: false,
    reviewers: [{type: "User", id: $reviewerId}],
    deployment_branch_policy: {
      protected_branches: true,
      custom_branch_policies: false
    }
  }')"
gh api \
  --method PUT \
  "repos/$REPOSITORY/environments/$GITHUB_ENVIRONMENT" \
  --input - <<<"$ENVIRONMENT_PAYLOAD" \
  --silent

set_var AZURE_ACR_NAME "$ACR_NAME"
set_var AZURE_RELEASE_CLIENT_ID "$RELEASE_CLIENT_ID"
set_var AZURE_SUBSCRIPTION_ID "$SUBSCRIPTION_ID"
set_var AZURE_TENANT_ID "$TENANT_ID"
gh variable set AZURE_API_APP_NAME --env "$GITHUB_ENVIRONMENT" --body "$API_APP_NAME"
gh variable set AZURE_API_FQDN --env "$GITHUB_ENVIRONMENT" --body "$API_FQDN"
gh variable set AZURE_DEPLOY_CLIENT_ID --env "$GITHUB_ENVIRONMENT" --body "$DEPLOY_CLIENT_ID"
gh variable set AZURE_RESOURCE_GROUP --env "$GITHUB_ENVIRONMENT" --body "$RESOURCE_GROUP"
gh variable set AZURE_WEB_APP_NAME --env "$GITHUB_ENVIRONMENT" --body "$WEB_APP_NAME"
gh variable set AZURE_WEB_FQDN --env "$GITHUB_ENVIRONMENT" --body "$WEB_FQDN"
say "No Azure client secret was created or stored."

stage "Release and verify"
say "The release workflow builds immutable images before the production approval gate."
DEFAULT_BRANCH="$(gh repo view --json defaultBranchRef --jq .defaultBranchRef.name)"
[[ "$DEFAULT_BRANCH" == "main" ]] || fail "The GitHub default branch is $DEFAULT_BRANCH, expected main"
RELEASE_SHA="$(gh api "repos/$REPOSITORY/git/ref/heads/main" --jq .object.sha)"
gh workflow view Production --repo "$REPOSITORY" >/dev/null ||
  fail "Production workflow is not available on main yet"
confirm "Start the production workflow for main commit $RELEASE_SHA?" ||
  fail "Initial release was not started"
gh workflow run Production --repo "$REPOSITORY" --ref main -f ref="$RELEASE_SHA"

RUN_ID=""
for attempt in $(seq 1 20); do
  RUN_ID="$(gh run list \
    --repo "$REPOSITORY" \
    --workflow Production \
    --event workflow_dispatch \
    --commit "$RELEASE_SHA" \
    --limit 1 \
    --json databaseId \
    --jq '.[0].databaseId // empty')"
  [[ -z "$RUN_ID" ]] || break
  test "$attempt" -lt 20
  sleep 3
done
[[ -n "$RUN_ID" ]] || fail "Could not find the dispatched production run"
RUN_URL="$(gh run view "$RUN_ID" --repo "$REPOSITORY" --json url --jq .url)"
open_url "$RUN_URL"
step "Wait for the release job to publish both image digests."
step "Click Review deployments, select production, and approve the deployment."
pause "Press Enter after approving the production deployment."
gh run watch "$RUN_ID" --repo "$REPOSITORY" --exit-status

PRODUCTION_URL="https://$WEB_FQDN"
curl --fail --silent --show-error "$PRODUCTION_URL/api/status" >/dev/null ||
  fail "Production smoke test failed at $PRODUCTION_URL/api/status"
say "Production is healthy: $PRODUCTION_URL"

finish
