// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetAuthenticatedPrincipalData, GetAuthenticatedPrincipalErrors, GetAuthenticatedPrincipalResponses, GetServiceStatusData, GetServiceStatusErrors, GetServiceStatusResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Authenticated Principal
 */
export const getAuthenticatedPrincipal = <ThrowOnError extends boolean = false>(options?: Options<GetAuthenticatedPrincipalData, ThrowOnError>): RequestResult<GetAuthenticatedPrincipalResponses, GetAuthenticatedPrincipalErrors, ThrowOnError> => (options?.client ?? client).get<GetAuthenticatedPrincipalResponses, GetAuthenticatedPrincipalErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/authenticated-principal',
    ...options
});

/**
 * Service Status
 */
export const getServiceStatus = <ThrowOnError extends boolean = false>(options?: Options<GetServiceStatusData, ThrowOnError>): RequestResult<GetServiceStatusResponses, GetServiceStatusErrors, ThrowOnError> => (options?.client ?? client).get<GetServiceStatusResponses, GetServiceStatusErrors, ThrowOnError>({ url: '/api/v1/status', ...options });
