// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://contracts` | (string & {});
};

/**
 * ApprovalRequestResponse
 */
export type ApprovalRequestResponse = {
    /**
     * Approval Id
     */
    approval_id: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Plan Revision Id
     */
    plan_revision_id: string;
};

/**
 * ApprovalResponse
 */
export type ApprovalResponse = {
    /**
     * Approval Request Id
     */
    approval_request_id: string;
    /**
     * Id
     */
    id: string;
    /**
     * Plan Revision Id
     */
    plan_revision_id: string;
};

/**
 * BoundApprovalActionRequest
 */
export type BoundApprovalActionRequest = {
    /**
     * Approval Request Id
     */
    approval_request_id: string;
    /**
     * Plan Revision Id
     */
    plan_revision_id: string;
};

/**
 * CreateTripRequest
 */
export type CreateTripRequest = {
    structure: TripStructureInput;
};

/**
 * HandbookExportFormat
 */
export type HandbookExportFormat = 'html';

/**
 * HandbookSnapshotResponse
 */
export type HandbookSnapshotResponse = {
    /**
     * Approval Id
     */
    approval_id: string;
    /**
     * Checksum
     */
    checksum: string;
    format: HandbookExportFormat;
    /**
     * Id
     */
    id: string;
    /**
     * Plan Revision Id
     */
    plan_revision_id: string;
};

/**
 * PlanClaimKind
 */
export type PlanClaimKind = 'travel_readiness';

/**
 * PlanClaimResponse
 */
export type PlanClaimResponse = {
    /**
     * Evidence Reference
     */
    evidence_reference: string;
    /**
     * Id
     */
    id: string;
    kind: PlanClaimKind;
    /**
     * Observed At
     */
    observed_at: string;
    /**
     * Text
     */
    text: string;
};

/**
 * PlanRevisionResponse
 */
export type PlanRevisionResponse = {
    /**
     * Base Revision Id
     */
    base_revision_id: string | null;
    /**
     * Claims
     */
    claims: Array<PlanClaimResponse>;
    /**
     * Id
     */
    id: string;
    /**
     * Revision Number
     */
    revision_number: number;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Trip Id
     */
    trip_id: string;
};

/**
 * PlannerPrincipalResponse
 */
export type PlannerPrincipalResponse = {
    /**
     * Planner Id
     */
    planner_id: string;
};

/**
 * ProblemResponse
 */
export type ProblemResponse = {
    /**
     * Code
     */
    code: string;
    /**
     * Detail
     */
    detail: string;
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Retryable
     */
    retryable: boolean;
    /**
     * Run Id
     */
    run_id?: string | null;
    /**
     * Status
     */
    status: number;
    /**
     * Title
     */
    title: string;
    /**
     * Type
     */
    type: string;
};

/**
 * RunResponse
 */
export type RunResponse = {
    /**
     * Id
     */
    id: string;
    status: RunStatus;
    terminal_outcome: RunTerminalOutcomeResponse | null;
    /**
     * Trip Id
     */
    trip_id: string;
};

/**
 * RunStatus
 */
export type RunStatus = 'Running' | 'Succeeded' | 'Blocked' | 'Failed' | 'Cancelled';

/**
 * RunTerminalOutcomeResponse
 */
export type RunTerminalOutcomeResponse = {
    /**
     * Code
     */
    code: string;
    /**
     * Detail
     */
    detail: string;
    status: RunTerminalStatus;
};

/**
 * RunTerminalStatus
 */
export type RunTerminalStatus = 'Succeeded' | 'Blocked' | 'Failed' | 'Cancelled';

/**
 * ServiceStatusResponse
 */
export type ServiceStatusResponse = {
    /**
     * Api Version
     */
    api_version: 'v1';
    /**
     * Service
     */
    service: 'flash-trips-api';
    /**
     * Status
     */
    status: 'ok';
};

/**
 * TripListResponse
 */
export type TripListResponse = {
    /**
     * Items
     */
    items: Array<TripResponse>;
};

/**
 * TripResponse
 */
export type TripResponse = {
    /**
     * Id
     */
    id: string;
    structure: TripStructureResponse;
};

/**
 * TripStayInput
 */
export type TripStayInput = {
    /**
     * City
     */
    city: string;
    /**
     * Ends On
     */
    ends_on: string;
    /**
     * Nights
     */
    nights: number;
    /**
     * Starts On
     */
    starts_on: string;
};

/**
 * TripStayResponse
 */
export type TripStayResponse = {
    /**
     * City
     */
    city: string;
    /**
     * Ends On
     */
    ends_on: string;
    /**
     * Id
     */
    id: string;
    /**
     * Nights
     */
    nights: number;
    /**
     * Starts On
     */
    starts_on: string;
};

/**
 * TripStructureInput
 */
export type TripStructureInput = {
    /**
     * Stays
     */
    stays: Array<TripStayInput>;
};

/**
 * TripStructureResponse
 */
export type TripStructureResponse = {
    /**
     * Stays
     */
    stays: Array<TripStayResponse>;
};

export type ApprovePlanRevisionData = {
    body: BoundApprovalActionRequest;
    path?: never;
    query?: never;
    url: '/api/v1/approvals';
};

export type ApprovePlanRevisionErrors = {
    /**
     * Unauthorized
     */
    401: ProblemResponse;
    /**
     * Forbidden
     */
    403: ProblemResponse;
    /**
     * Approval Not Found
     */
    404: ProblemResponse;
    /**
     * Approval Already Recorded
     */
    409: ProblemResponse;
    /**
     * Unprocessable Request
     */
    422: ProblemResponse;
    /**
     * Internal Server Error
     */
    500: ProblemResponse;
};

export type ApprovePlanRevisionError = ApprovePlanRevisionErrors[keyof ApprovePlanRevisionErrors];

export type ApprovePlanRevisionResponses = {
    /**
     * Successful Response
     */
    201: ApprovalResponse;
};

export type ApprovePlanRevisionResponse = ApprovePlanRevisionResponses[keyof ApprovePlanRevisionResponses];

export type GetAuthenticatedPrincipalData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/authenticated-principal';
};

export type GetAuthenticatedPrincipalErrors = {
    /**
     * Unauthorized
     */
    401: ProblemResponse;
    /**
     * Forbidden
     */
    403: ProblemResponse;
    /**
     * Not Found
     */
    404: ProblemResponse;
    /**
     * Internal Server Error
     */
    500: ProblemResponse;
};

export type GetAuthenticatedPrincipalError = GetAuthenticatedPrincipalErrors[keyof GetAuthenticatedPrincipalErrors];

export type GetAuthenticatedPrincipalResponses = {
    /**
     * Successful Response
     */
    200: PlannerPrincipalResponse;
};

export type GetAuthenticatedPrincipalResponse = GetAuthenticatedPrincipalResponses[keyof GetAuthenticatedPrincipalResponses];

export type DownloadHandbookData = {
    body?: never;
    path: {
        /**
         * Snapshot Id
         */
        snapshot_id: string;
    };
    query?: never;
    url: '/api/v1/handbook-snapshots/{snapshot_id}/export';
};

export type DownloadHandbookErrors = {
    /**
     * Unauthorized
     */
    401: ProblemResponse;
    /**
     * Forbidden
     */
    403: ProblemResponse;
    /**
     * Handbook Not Found
     */
    404: ProblemResponse;
    /**
     * Handbook Not Eligible
     */
    409: ProblemResponse;
    /**
     * Unprocessable Request
     */
    422: ProblemResponse;
    /**
     * Internal Server Error
     */
    500: ProblemResponse;
};

export type DownloadHandbookError = DownloadHandbookErrors[keyof DownloadHandbookErrors];

export type DownloadHandbookResponses = {
    /**
     * Handbook HTML export
     */
    200: Blob | File;
};

export type DownloadHandbookResponse = DownloadHandbookResponses[keyof DownloadHandbookResponses];

export type GetRunData = {
    body?: never;
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/api/v1/runs/{run_id}';
};

export type GetRunErrors = {
    /**
     * Unauthorized
     */
    401: ProblemResponse;
    /**
     * Forbidden
     */
    403: ProblemResponse;
    /**
     * Not Found
     */
    404: ProblemResponse;
    /**
     * Unprocessable Request
     */
    422: ProblemResponse;
    /**
     * Internal Server Error
     */
    500: ProblemResponse;
};

export type GetRunError = GetRunErrors[keyof GetRunErrors];

export type GetRunResponses = {
    /**
     * Successful Response
     */
    200: RunResponse;
};

export type GetRunResponse = GetRunResponses[keyof GetRunResponses];

export type GetServiceStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/status';
};

export type GetServiceStatusErrors = {
    /**
     * Not Found
     */
    404: ProblemResponse;
    /**
     * Internal Server Error
     */
    500: ProblemResponse;
};

export type GetServiceStatusError = GetServiceStatusErrors[keyof GetServiceStatusErrors];

export type GetServiceStatusResponses = {
    /**
     * Successful Response
     */
    200: ServiceStatusResponse;
};

export type GetServiceStatusResponse = GetServiceStatusResponses[keyof GetServiceStatusResponses];

export type ListTripsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/trips';
};

export type ListTripsErrors = {
    /**
     * Unauthorized
     */
    401: ProblemResponse;
    /**
     * Forbidden
     */
    403: ProblemResponse;
    /**
     * Not Found
     */
    404: ProblemResponse;
    /**
     * Internal Server Error
     */
    500: ProblemResponse;
};

export type ListTripsError = ListTripsErrors[keyof ListTripsErrors];

export type ListTripsResponses = {
    /**
     * Successful Response
     */
    200: TripListResponse;
};

export type ListTripsResponse = ListTripsResponses[keyof ListTripsResponses];

export type CreateTripData = {
    body: CreateTripRequest;
    path?: never;
    query?: never;
    url: '/api/v1/trips';
};

export type CreateTripErrors = {
    /**
     * Unauthorized
     */
    401: ProblemResponse;
    /**
     * Forbidden
     */
    403: ProblemResponse;
    /**
     * Not Found
     */
    404: ProblemResponse;
    /**
     * Unprocessable Request
     */
    422: ProblemResponse;
    /**
     * Internal Server Error
     */
    500: ProblemResponse;
};

export type CreateTripError = CreateTripErrors[keyof CreateTripErrors];

export type CreateTripResponses = {
    /**
     * Successful Response
     */
    201: TripResponse;
};

export type CreateTripResponse = CreateTripResponses[keyof CreateTripResponses];

export type GetTripData = {
    body?: never;
    path: {
        /**
         * Trip Id
         */
        trip_id: string;
    };
    query?: never;
    url: '/api/v1/trips/{trip_id}';
};

export type GetTripErrors = {
    /**
     * Unauthorized
     */
    401: ProblemResponse;
    /**
     * Forbidden
     */
    403: ProblemResponse;
    /**
     * Trip Not Found
     */
    404: ProblemResponse;
    /**
     * Unprocessable Request
     */
    422: ProblemResponse;
    /**
     * Internal Server Error
     */
    500: ProblemResponse;
};

export type GetTripError = GetTripErrors[keyof GetTripErrors];

export type GetTripResponses = {
    /**
     * Successful Response
     */
    200: TripResponse;
};

export type GetTripResponse = GetTripResponses[keyof GetTripResponses];

export type GetCurrentApprovalRequestData = {
    body?: never;
    path: {
        /**
         * Trip Id
         */
        trip_id: string;
    };
    query?: never;
    url: '/api/v1/trips/{trip_id}/approval-request';
};

export type GetCurrentApprovalRequestErrors = {
    /**
     * Unauthorized
     */
    401: ProblemResponse;
    /**
     * Forbidden
     */
    403: ProblemResponse;
    /**
     * Approval Not Found
     */
    404: ProblemResponse;
    /**
     * Approval Already Recorded
     */
    409: ProblemResponse;
    /**
     * Unprocessable Request
     */
    422: ProblemResponse;
    /**
     * Internal Server Error
     */
    500: ProblemResponse;
};

export type GetCurrentApprovalRequestError = GetCurrentApprovalRequestErrors[keyof GetCurrentApprovalRequestErrors];

export type GetCurrentApprovalRequestResponses = {
    /**
     * Successful Response
     */
    200: ApprovalRequestResponse;
};

export type GetCurrentApprovalRequestResponse = GetCurrentApprovalRequestResponses[keyof GetCurrentApprovalRequestResponses];

export type CompileHandbookData = {
    body?: never;
    path: {
        /**
         * Trip Id
         */
        trip_id: string;
    };
    query?: never;
    url: '/api/v1/trips/{trip_id}/handbook-snapshots';
};

export type CompileHandbookErrors = {
    /**
     * Unauthorized
     */
    401: ProblemResponse;
    /**
     * Forbidden
     */
    403: ProblemResponse;
    /**
     * Handbook Not Found
     */
    404: ProblemResponse;
    /**
     * Handbook Not Eligible
     */
    409: ProblemResponse;
    /**
     * Unprocessable Request
     */
    422: ProblemResponse;
    /**
     * Internal Server Error
     */
    500: ProblemResponse;
};

export type CompileHandbookError = CompileHandbookErrors[keyof CompileHandbookErrors];

export type CompileHandbookResponses = {
    /**
     * Successful Response
     */
    201: HandbookSnapshotResponse;
};

export type CompileHandbookResponse = CompileHandbookResponses[keyof CompileHandbookResponses];

export type GetCurrentPlanRevisionData = {
    body?: never;
    path: {
        /**
         * Trip Id
         */
        trip_id: string;
    };
    query?: never;
    url: '/api/v1/trips/{trip_id}/plan-revision';
};

export type GetCurrentPlanRevisionErrors = {
    /**
     * Unauthorized
     */
    401: ProblemResponse;
    /**
     * Forbidden
     */
    403: ProblemResponse;
    /**
     * Plan Revision Not Found
     */
    404: ProblemResponse;
    /**
     * Unprocessable Request
     */
    422: ProblemResponse;
    /**
     * Internal Server Error
     */
    500: ProblemResponse;
};

export type GetCurrentPlanRevisionError = GetCurrentPlanRevisionErrors[keyof GetCurrentPlanRevisionErrors];

export type GetCurrentPlanRevisionResponses = {
    /**
     * Successful Response
     */
    200: PlanRevisionResponse;
};

export type GetCurrentPlanRevisionResponse = GetCurrentPlanRevisionResponses[keyof GetCurrentPlanRevisionResponses];

export type StartRunData = {
    body?: never;
    path: {
        /**
         * Trip Id
         */
        trip_id: string;
    };
    query?: never;
    url: '/api/v1/trips/{trip_id}/runs';
};

export type StartRunErrors = {
    /**
     * Unauthorized
     */
    401: ProblemResponse;
    /**
     * Forbidden
     */
    403: ProblemResponse;
    /**
     * Not Found
     */
    404: ProblemResponse;
    /**
     * Conflict
     */
    409: ProblemResponse;
    /**
     * Unprocessable Request
     */
    422: ProblemResponse;
    /**
     * Internal Server Error
     */
    500: ProblemResponse;
};

export type StartRunError = StartRunErrors[keyof StartRunErrors];

export type StartRunResponses = {
    /**
     * Successful Response
     */
    202: RunResponse;
};

export type StartRunResponse = StartRunResponses[keyof StartRunResponses];
