// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://contracts` | (string & {});
};

/**
 * ProblemResponse
 */
export type ProblemResponse = {
    /**
     * Code
     */
    code: string;
    /**
     * Detail
     */
    detail: string;
    /**
     * Request Id
     */
    request_id: string;
    /**
     * Retryable
     */
    retryable: boolean;
    /**
     * Status
     */
    status: number;
    /**
     * Title
     */
    title: string;
    /**
     * Type
     */
    type: string;
};

/**
 * ServiceStatusResponse
 */
export type ServiceStatusResponse = {
    /**
     * Api Version
     */
    api_version: 'v1';
    /**
     * Service
     */
    service: 'flash-trips-api';
    /**
     * Status
     */
    status: 'ok';
};

export type GetServiceStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/status';
};

export type GetServiceStatusErrors = {
    /**
     * Not Found
     */
    404: ProblemResponse;
    /**
     * Internal Server Error
     */
    500: ProblemResponse;
};

export type GetServiceStatusError = GetServiceStatusErrors[keyof GetServiceStatusErrors];

export type GetServiceStatusResponses = {
    /**
     * Successful Response
     */
    200: ServiceStatusResponse;
};

export type GetServiceStatusResponse = GetServiceStatusResponses[keyof GetServiceStatusResponses];
